// Placeholder — run `npm run db:types` to generate from Supabase
// This file will be auto-generated by: supabase gen types typescript
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type Database = Record<string, never>;
